### ISSUE TITLE
Remove unexpected scripts in README.md

### ISSUE THREAD

**Issue by AsaiToshiya** [fl4viooliveira/4devbydev#20]
https://github.com/fl4viooliveira/4devbydev/blob/ad26b4fbc3568fb4651c6c394bdcfb13bb150afe/README.md?plain=1#L33-L34

This causes the "Getting Started with Printful" not to display properly.

![Screenshot](https://user-images.githubusercontent.com/18229040/170829387-d408895c-e8f4-49f5-a111-ae1189d75397.png)

**Comment by fl4viooliveira** [comment]
Thank you AsaiToshiya, I can fix that, or if you prefer you can do a pull request.

**Comment by AsaiToshiya** [comment]
I'm going to close this too.
