### ISSUE TITLE
Fix run script in README.md

### ISSUE THREAD

**Issue by AsaiToshiya** [fl4viooliveira/4devbydev#21]
Fix `npm dev` to `npm run dev`.

https://github.com/fl4viooliveira/4devbydev/blob/ad26b4fbc3568fb4651c6c394bdcfb13bb150afe/README.md?plain=1#L79

**Comment by fl4viooliveira** [comment]
Thank you @AsaiToshiya. I can fix it, you can do a pull request.

**Comment by AsaiToshiya** [comment]
Do you have a guide for the emoji in the commit message?

**Comment by fl4viooliveira** [comment]
I use this guide on my commits: [gitmoji](https://github.com/carloscuesta/gitmoji).
But it's not a problem if you commit without emoji, no problem at all.
